<?php
    $this->headTitle('Sign Up');
?>

<div class="banner_title">
    <span>Sign Up</span>
</div>


<div class="grid2col clearfix">

    <div class="col_right_wrap">

        <div class="col_right">
            <!-- sidebar is empty for now -->
        </div>
    </div>

    <div class="col_left_wrap">

        <div class="col_left">

            <h1 class="hilite"><?php echo $this->translate('signup_heading');?></h1>

            <?php echo $this->form; ?>

        </div>

    </div>

</div>