<?php
    $this->headTitle('Add List');
?>

<div class="banner_title">
    <span>Add To-do List</span>
</div>


<div class="grid2col clearfix">

    <div class="col_right_wrap">

        <div class="col_right">

        </div>
    </div>

    <div class="col_left_wrap">

        <div class="col_left">

            <h1 class="hilite"><?php echo $this->translate('addlist_heading');?></h1>

            <?php echo $this->form; ?>


        </div>

    </div>

</div>
